### ISSUE TITLE
OAuth认证时出现问题

### ISSUE THREAD

**Issue by Andy-Chuck** [bs-community/flarum-oauth-client#1]
使用本插件时出现错误，提示

`Argument 2 passed to Flarum\Forum\Auth\ResponseFactory::make() must be of the type string, null given, called in......`

更换为fof的passport插件后同样出现该错误。
passport 插件的错误出现在 /vendor/flarum/core/src/Forum/Auth/ResponseFactory.php 第35行，认为可能是BS Server的Oauth有问题。

![IMG](https://user-images.githubusercontent.com/54295429/91725331-28988d80-ebd1-11ea-92a3-59bc3e25ec49.png)

**Comment by g-plane** [comment]
BS 的 OAuth 不是由我们自己实现的，有问题的话一般是上游的问题。
