### ISSUE TITLE
登录时出现500错误

### ISSUE THREAD

**Issue by Rabbit0w0** [bs-community/flarum-oauth-client#2]
Flarum版本 beta15
严格按照官方教程安装了本插件后无法使用Blessing登录，显示500错误

**Comment by CraftDream** [comment]
![图](https://user-images.githubusercontent.com/47418954/106359744-859a9a00-634f-11eb-9fd5-cf5a3e6c5370.png)

**Comment by CraftDream** [comment]
![图](https://user-images.githubusercontent.com/47418954/106359744-859a9a00-634f-11eb-9fd5-cf5a3e6c5370.png)

**Comment by g-plane** [comment]
没有足够的信息来排查问题。

**Comment by Rabbit0w0** [comment]
http://admin.5imczy.cn:35240 这是论坛网址由于Blessing的限制，我们无法获得错误日志

**Comment by g-plane** [comment]
Blessing Skin 从来没有这方面的限制。既然你取不到日志，我也没法了解问题。

**Comment by CraftDream** [comment]
> Blessing Skin 从来没有这方面的限制。既然你取不到日志，我也没法了解问题。

PHP的errorlog里确实没有任何东西。但页面上显示查看控制台，控制台内只有一个500错误。会不会是不兼容最新的beta.15或者是其他原因？

**Comment by g-plane** [comment]
已经针对新版适配过。另外我需要的是 BS 自己的日志，也就是 Laravel 的日志。请把它放在 pastebin 上，不要直接贴到 issue 中。

**Comment by CraftDream** [comment]
> 已经针对新版适配过。另外我需要的是 BS 自己的日志，也就是 Laravel 的日志。请把它放在 pastebin 上，不要直接贴到 issue 中。

Flarum的log需要吗

**Comment by CraftDream** [comment]
BS的log太长了，pastebin502了可还行

**Comment by CraftDream** [comment]
https://paste.ubuntu.com/p/Nby2C59Sck/

**Comment by g-plane** [comment]
你倒是节选最新的那些啊……

**Comment by CraftDream** [comment]
这就是出错时间附近的log

**Comment by g-plane** [comment]
那你也把 Flarum 日志发过来吧，但是我不熟悉 Flarum，不一定能解决问题。

**Comment by CraftDream** [comment]
https://paste.ubuntu.com/p/BJSkG2wHPK/

**Comment by CraftDream** [comment]
估计就在这里面出的问题，我看到了oauth2

**Comment by g-plane** [comment]
我感觉是你那边没有配置好？有看过我们的手册吗？

**Comment by CraftDream** [comment]
> 我感觉是你那边没有配置好？有看过我们的手册吗？

有，id和key都没问题

**Comment by g-plane** [comment]
那我就不太清楚了，请谅解。

**Comment by CraftDream** [comment]
https://paste.ubuntu.com/p/NRj4rBBSTz/

**Comment by CraftDream** [comment]
https://paste.ubuntu.com/p/XbzxZwXrxZ/

**Comment by g-plane** [comment]
目前我没有办法和条件去重现 Flarum 与 Blessing Skin 的对接环境，而且我对 Flarum 扩展开发也了解不多，暂时无法帮助你解决问题。

**Comment by CraftDream** [comment]
应该是blessingskin那边oauth的问题，我刚刚给flarum装上fof的passport插件配置好还是出现这个同样的错误
